name: Example Workflow

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME_SERVER: server

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Modify IMAGE_NAME_SERVER
        id: modify
        run: |
          echo "IMAGE_NAME_SERVER_NEW=${{ env.IMAGE_NAME_SERVER }}-debug" >> "$GITHUB_ENV"
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use modified IMAGE_NAME_SERVER
        run: |
          echo "Using modified IMAGE_NAME_SERVER: ${{ env.IMAGE_NAME_SERVER_NEW }}"
