name: CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'

env:
  REGISTRY: yangfanz/
  ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com/yangfanz/
  IMAGE_NAME_SERVER: server
  IMAGE_NAME_TIMER: timer
  IMAGE_NAME_MASTER: master
  IMAGE_NAME_WORK: work
  IMAGE_NAME_WEB: web
  IMAGE_NAME_RUN: run
  IMAGE_TAG: v1.${{ github.run_number }}
  
jobs:
  set-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag event
        id: check_tag
        run: echo ::set-output name=is_tag::$(echo "${{ github.ref }}" | grep -E '^refs/tags/')


      - name: Set IMAGE_TAG
        id: reset_image_tag
        if: steps.check_tag.outputs.is_tag == ${{ github.ref }}" | grep -E '^refs/tags/')
        run: |
          TAG=$(echo "${{ github.ref }}" | sed -e 's|^refs/tags/||')
          echo "IMAGE_TAG=${TAG}"


      - name: Show IMAGE_TAG
        run: echo "IMAGE_TAG is ${{ env.IMAGE_TAG }}"
      - name: Modify env variables
        id: output
        if: steps.check_tag.outputs.is_tag != ${{ github.ref }}" | grep -E '^refs/tags/')
        run: |
          image_name"=-debug" 
      


      - name: Set IMAGE_TAG image_name
        run: |
          echo "IMAGE_TAG=${TAG}"
          echo "IMAGE_TAG=${image_name}"name: Example Workflow
