name: Example Workflow
on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'

env:
  image_suffix: ''

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Determine image_suffix
        id: determine
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            echo "::set-output name=image_suffix::debug"
          else
            echo "::set-output name=image_suffix::release"
          fi
      - name: Show image_suffix
        run: |
          echo "image_suffix is ${{ steps.determine.outputs.image_suffix }}"
