name: Example Workflow
on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'

env:
  image_suffix: ''
  IMAGE_TAG: v1.${{ github.run_number }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Determine image_tag and image_suffix
        id: determine
        run: |
          if [[ ${{ github.event_name }} == 'push' && ${{ github.ref }} == 'refs/tags/*' ]]; then
            image_tag=${{ github.ref }}
            image_suffix=''
          else
            image_tag=${{ env.IMAGE_TAG }}
            image_suffix='debug'
          fi
          echo "::set-output name=image_tag::${image_tag}"
          echo "::set-output name=image_suffix::${image_suffix}"
      - name: Show image_tag and image_suffix
        run: |
          echo "image_tag is ${{ steps.determine.outputs.image_tag }}"
          echo "image_suffix is ${{ steps.determine.outputs.image_suffix }}"
